name: daily-report-ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        # 🔥 Enable pip cache tied to requirements.txt
        cache: 'pip'
        cache-dependency-path: requirements.txt

    - name: Install dependencies
      run: |
        python -m venv .venv
        source .venv/bin/activate
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        # belt-and-braces: make sure Jinja2 is present
        pip show Jinja2 || pip install Jinja2
        python -c "import jinja2; print('Jinja2 OK:', jinja2.__version__)"

    - name: Stock CSV validation
      run: .venv/bin/python src/validators/stock_validator.py

    - name: Bond CSV validation
      run: .venv/bin/python src/validators/bond_validator.py

    - name: Render smoke email
      run: |
        source .venv/bin/activate
        ./scripts/render_email_smoke.sh
